import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  //    tutorialSidebar: [
  //     {
  //       type: 'doc',
  //       id: 'getting-started',
  //       label: 'Getting Started',
  //     },
  //     {
  //       type: 'category',
  //       label: 'Welcome',
  //       items: ['welcome/introduction'],
  //       collapsed: false,
  //     },
  //     {
  //       type: 'doc',
  //       id: 'authentication',
  //       label: 'Authentication',
  //     },
  //     {
  //       type: 'doc',
  //       id: 'errors',
  //       label: 'Errors',
  //     },
  //     {
  //       type: 'doc',
  //       id: 'sdk',
  //       label: 'SDK',
  //     },
  //     {
  //       type: 'doc',
  //       id: 'libraries',
  //       label: 'Libraries',
  //     },
  //     {
  //       type: 'doc',
  //       id: 'users',
  //       label: 'Users',
  //     },
  //     {
  //       type: 'doc',
  //       id: 'charge-authorization',
  //       label: 'Charge Authorization',
  //     },
  //   ],
  // };
};

export default sidebars;
